[package]
name = "dtg-storage-fjall"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
tck = []

[lints]
workspace = true

[dependencies]
bincode = { version = "=2.0.1", features = ["derive"] }
blake3 = "=1.8.5"
dtg-storage = { path = "../dtg-storage" }
fjall = "=3.1.8"

[dev-dependencies]
tempfile = "3"

[[test]]
name = "storage_tck"
path = "tests/storage_tck.rs"
required-features = ["tck"]
