[package]
name = "temporal-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
storage-api = { path = "../storage-api" }
temporal-types = { path = "../temporal-types" }

[dev-dependencies]
adapter-memory = { path = "../adapter-memory" }
temporal-model = { path = "../temporal-model" }

[lints]
workspace = true
