[workspace]
members = [
    "crates/kernel/dtg-kernel",
    "crates/language/dtg-language-ir",
    "crates/language/dtg-language",
    "crates/storage/dtg-storage",
    "crates/storage/dtg-storage-fjall",
    "crates/storage/dtg-storage-postgres",
    "crates/storage/dtg-storage-kuzu",
    "crates/storage/dtg-storage-remote-protocol",
    "crates/storage/dtg-storage-remote",
    "crates/execution/dtg-plan",
    "crates/execution/dtg-query",
    "crates/execution/dtg-transaction",
    "crates/execution/dtg-shard",
    "crates/execution/dtg-analytics",
    "crates/execution/dtg-snapshot-csr",
    "crates/execution/dtg-control",
    "crates/execution/dtg-cluster-protocol",
    "crates/execution/dtg-execution",
    "crates/processes/dtg-gateway",
    "crates/processes/dtg-data",
    "crates/processes/dtg-meta",
    "crates/processes/dtg-controller",
]
resolver = "3"

[workspace.package]
version = "1.0.0"
edition = "2024"
rust-version = "1.93"
license = "Apache-2.0"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
