[package]
name = "dtg-language"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
dtg-kernel = { path = "../../kernel/dtg-kernel" }
dtg-language-ir = { path = "../dtg-language-ir" }

[dev-dependencies]
dtg-language-ir = { path = "../dtg-language-ir" }
