[package]
name = "cypher-compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
blake3 = "=1.8.5"
cypher-ast = { path = "../cypher-ast" }
cypher-sema = { path = "../cypher-sema" }
cypher-syntax = { path = "../cypher-syntax" }
temporal-ir = { path = "../temporal-ir" }
temporal-types = { path = "../temporal-types" }

[lints]
workspace = true
