[package]
name = "adapter-postgres"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
adapter-registry = { path = "../adapter-registry" }
adapter-sidecar = { path = "../adapter-sidecar" }
blake3 = "=1.8.5"
fallible-iterator = "=0.2.0"
postgres = "=0.19.14"
storage-api = { path = "../storage-api" }
temporal-storage = { path = "../temporal-storage" }
temporal-types = { path = "../temporal-types" }

[dev-dependencies]
adapter-rocksdb = { path = "../adapter-rocksdb" }
storage-api = { path = "../storage-api", features = ["mapping-tck"] }
tempfile = "3"

[lints]
workspace = true
