[package]
name = "analytics-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
analytics-api = { path = "../analytics-api" }
storage-api = { path = "../storage-api" }
temporal-storage = { path = "../temporal-storage" }
temporal-types = { path = "../temporal-types" }

[dev-dependencies]
adapter-memory = { path = "../adapter-memory" }

[lints]
workspace = true
