[package]
name = "dtg-transaction"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
blake3 = "1"
dtg-kernel = { path = "../../kernel/dtg-kernel" }
dtg-storage = { path = "../../storage/dtg-storage" }

[dev-dependencies]
dtg-shard = { path = "../dtg-shard" }
dtg-storage-fjall = { path = "../../storage/dtg-storage-fjall" }
tempfile = "3"
