[package]
name = "replica-snapshot"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
adapter-rocksdb = { path = "../adapter-rocksdb" }
blake3 = "=1.8.5"
crc32fast = "=1.5.0"
shard-runtime = { path = "../shard-runtime" }
storage-api = { path = "../storage-api" }
temporal-types = { path = "../temporal-types" }

[dev-dependencies]
raft-command = { path = "../raft-command" }
tempfile = "3"

[lints]
workspace = true
