[package]
name = "query-executor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
storage-api = { path = "../storage-api" }
temporal-ir = { path = "../temporal-ir" }
temporal-storage = { path = "../temporal-storage" }
temporal-types = { path = "../temporal-types" }

[dev-dependencies]
adapter-memory = { path = "../adapter-memory" }
adapter-rocksdb = { path = "../adapter-rocksdb" }
tempfile = "3"

[lints]
workspace = true
