[package]
name = "dtg-storage-neo4j"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
base64 = "=0.22.1"
dtg-kernel = { path = "../../kernel/dtg-kernel" }
dtg-storage = { path = "../dtg-storage" }
serde_json = "=1.0.145"
tokio = { version = "=1.53.0", features = ["rt", "sync"] }
ureq = { version = "=2.12.1", features = ["json"] }

[dev-dependencies]
tokio = { version = "=1.53.0", features = ["macros", "rt-multi-thread"] }
