[package]
name = "distributed-query"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
blake3 = "=1.8.5"
physical-plan = { path = "../physical-plan" }
query-executor = { path = "../query-executor", default-features = false }
storage-api = { path = "../storage-api" }
temporal-storage = { path = "../temporal-storage" }
temporal-types = { path = "../temporal-types" }

[dev-dependencies]
adapter-memory = { path = "../adapter-memory" }
temporal-ir = { path = "../temporal-ir" }

[lints]
workspace = true
