[package]
name = "analytics-ledger"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
analytics-api = { path = "../analytics-api" }
blake3 = "=1.8.5"
crc32fast = "=1.5.0"
temporal-types = { path = "../temporal-types" }

[dev-dependencies]
raft-command = { path = "../raft-command" }

[lints]
workspace = true
