[package]
name = "dtg-plan"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
dtg-kernel = { path = "../../kernel/dtg-kernel" }
dtg-language-ir = { path = "../../language/dtg-language-ir" }
dtg-storage = { path = "../../storage/dtg-storage" }

[lints]
workspace = true
