[package]
name = "adapter-memory"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
storage-api = { path = "../storage-api" }

[dev-dependencies]
temporal-storage = { path = "../temporal-storage" }
temporal-types = { path = "../temporal-types" }

[lints]
workspace = true
